#!/bin/bash

INTERVAL=10
WIFI_MGMT=wifi_mgmt
LED_CTRL=mx_led_control

_signal_led_flush() {
	slot=$1
	#echo "${LED_CTRL} signal off ${slot} 1"
	${LED_CTRL} signal off ${slot} 1 &> /dev/null
	${LED_CTRL} signal off ${slot} 2 &> /dev/null
	${LED_CTRL} signal off ${slot} 3 &> /dev/null
}

_signal_led() {
	slot=$1
	signal=$2

	#echo slot: $slot
	#echo signal: $signal
	if  echo "$signal" | grep -q "N/A"; then
		_signal_led_flush ${slot}
		return
	fi

	signal=$(echo "$signal" | awk 'END {print $(NF-1)}')
	if [ $signal -ge -30 ]; then
		#echo "Excellent"
		${LED_CTRL} signal on ${slot} 1 &> /dev/null
		${LED_CTRL} signal on ${slot} 2 &> /dev/null
		${LED_CTRL} signal on ${slot} 3 &> /dev/null
	elif [ $signal -ge -70 ]; then
		#echo "Fair"
		${LED_CTRL} signal on ${slot} 1 &> /dev/null
		${LED_CTRL} signal on ${slot} 2 &> /dev/null
		${LED_CTRL} signal off ${slot} 3 &> /dev/null
	elif [ $signal -ge -80 ]; then
		#echo "Poor"
		${LED_CTRL} signal on ${slot} 1 &> /dev/null
		${LED_CTRL} signal off ${slot} 2 &> /dev/null
		${LED_CTRL} signal off ${slot} 3 &> /dev/null
	else
		#echo "No signal"
		_signal_led_flush ${slot}
	fi
}

_loop() {
	while [ 1 ]; do
		modules=$(${WIFI_MGMT} interfaces)
		for i in $(seq 0 $((modules-1))); do
			slot=$(${WIFI_MGMT} -i wlan$i slot)
			signal=$(${WIFI_MGMT} -i wlan$i signal)
			_signal_led ${slot} "${signal}"
		done
		sleep ${INTERVAL}
	done
}

usage() {
	echo "Usage:"
	echo "  $1 [OPTION]"
	echo ""
	echo "Options:"
	echo "  -i <polling interval>"
	echo "		Polling interval in seconds to update the signal LED"
	echo "  -h"
	echo "		Show help"
	echo "  -v"
	echo "		Print version"
}


while getopts  "i:vh" flag; do
	if [ "${flag}" == "i" ]; then
		re='^[0-9]+$'
		if ! [[ $OPTARG =~ $re ]] ; then
			   echo "error: Interval should be a number" >&2
			   usage $0
			   exit 1
		fi
		INTERVAL=$OPTARG
	elif [ "${flag}" == "h" ]; then
		usage $0
		exit 0
	elif [ "${flag}" == "v" ]; then
		${WIFI_MGMT} version
		exit 0
	fi
done

_loop
